app/main/forms.py
# coding: utf-8
from flask_wtf import Form
# from wtforms import
# from wtforms.validators import

app/main/__init__.py
# coding: utf-8

from flask import Blueprint

main = Blueprint(
    'main',
    __name__,
    template_folder = 'templates',
    static_folder = 'static'
)

from . import views, forms

app/main/views.py
# coding: utf-8
from .. import app
from . import main
from ..models import Movie, Article, Photo, Anime, Course, Startup, Notice
# from ..models import W_Movie, W_Article, W_Photo, W_Anime, W_Course, W_Startup
from app import db, r1
from flask import render_template, request, redirect, url_for, send_from_directory, flash, session, jsonify
from geetest import GeetestLib
# from werkzeug import secure_filename
import time
import os
import random


captcha_id = app.config['CAPTCHA_ID']
private_key = app.config['PRIVATE_KEY']
pic_appendix = app.config['PIC_APPENDIX']


def allowed_file(filename):
    if '.' in filename and \
            filename.rsplit('.', 1)[1] in app.config['ALLOWED_EXTENSIONS']:
                return True

@main.route('/')
def index():
    movies = Movie.query.filter_by(is_confirm=True).all()
    courses = Course.query.filter_by(is_confirm=True).all()
    animes = Anime.query.filter_by(is_confirm=True).all()
    photos = Photo.query.filter_by(is_confirm=True).all()
    startups = Startup.query.filter_by(is_confirm=True).all()
    for eachPhoto in photos:
        eachPhoto.first_photo = eachPhoto.video_url.split(' ')[0]
    articles = Article.query.filter_by(is_confirm=True).all()
    notices = Notice.query.filter_by(is_confirm=True).all()
    return render_template(
            '/main/index.html',
            movies=movies[:4],
            courses=courses[:3],
            animes=animes[:3],
            photos=photos[:3],
            articles=articles[:3],
            notices=notices[:3],
            startups=startups[:3]
            )

@main.route('/upload/', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        tag = request.form.get('upload-class-choice')
        file_name = request.form.get('file_name')
        description = request.form.get('description') or ''

        if not tag:
            flash("请选择类型!")
            return redirect(url_for('main.upload_file'))

        if not file_name:
            flash("请填写文件名!")
            return redirect(url_for('main.upload_file'))

        author_name = request.form.get('author_name')
        if not author_name:
            flash("请填写文件名!")
            return redirect(url_for('main.upload_file'))

        img_url = request.form.get('img_url')

        if not img_url and tag is not 'article':
            flash("请添加头图链接!")
            return redirect(url_for('main.upload_file'))
        
        upload_url = request.form.get('upload_url')

        if not upload_url:
            file = request.files['file']
            if allowed_file(file.filename):
                filename = time.strftime("%a %b %d %H:%M:%S %Y",
                        time.localtime()) + ' ' + file_name + '.' + file.filename.rsplit('.', 1)[1]
            else:
                flash("请添加文件压缩包或链接!")
                return redirect(url_for('main.upload_file'))
        else:
            filename = time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()) + ' ' + file_name

        if tag == 'movie':
            UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'movie/')
            if not upload_url:
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Movie(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )

        elif tag == 'article':
            if not upload_url:
                UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'article/')
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Article(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )

        elif tag == 'photo':
            if not upload_url:
                UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'photo/')
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Photo(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )
        elif tag == 'anime':
            if not upload_url:
                UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'anime/')
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Anime(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )

        elif tag == 'course':
            if not upload_url:
                UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'course/')
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Course(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )

        elif tag == 'startup':
            if not upload_url:
                UPLOAD_FOLDER = os.path.join(app.config['BUPLOAD_FOLDER'], 'startup/')
                file.save(os.path.join(UPLOAD_FOLDER, filename))
            else:
                UPLOAD_FOLDER = 'no'
            item = Startup(
                    upload_name=filename,
                    present_name=file_name,
                    author_name=author_name,
                    description=description,
                    upload_url=UPLOAD_FOLDER + filename,
                    video_url=upload_url,
                    img_url = img_url,
                    a_time=(time.strftime("%a %b %d %H:%M:%S %Y",time.localtime()))[:10]
                    )

        db.session.add(item)
        db.session.commit()
        flash("文件已上传!正在审核中···")
        return redirect(url_for('main.upload_file'))
    return render_template('/main/upload.html')


@main.route('/notices/')
def notices():
    notices = Notice.query.filter_by(is_confirm=True).all()
    return render_template('/main/notices.html', notices=notices)


@main.route('/movies/')
def movies():
    movies = Movie.query.filter_by(is_confirm=True).all()
    return render_template('main/movies.html', movies=movies)


@main.route('/animes/')
def animes():
    animes = Anime.query.filter_by(is_confirm=True).all()
    return render_template('main/animes.html', animes=animes)


@main.route('/courses/')
def courses():
    courses = Course.query.filter_by(is_confirm=True).all()
    return render_template('main/courses.html', courses=courses)


@main.route('/photos/')
def photos():
    photos = Photo.query.filter_by(is_confirm=True).all()
    for eachPhoto in photos:
        eachPhoto.first_photo = eachPhoto.upload_url.split(' ')[0]
    return render_template('main/photos.html', photos=photos)


@main.route('/articles/')
def articles():
    articles = Article.query.filter_by(is_confirm=True).all()
    return render_template('main/articles.html', articles=articles)


@main.route('/startups/')
def startups():
    startups = Startup.query.filter_by(is_confirm=True).all()
    return render_template('main/startups.html', startups=startups)


@main.route('/rank/')
def rank():
    movies = Movie.query.filter_by(is_confirm=True).all()
    articles = Article.query.filter_by(is_confirm=True).all()
    animes = Anime.query.filter_by(is_confirm=True).all()
    photos = Photo.query.filter_by(is_confirm=True).all()
    courses = Course.query.filter_by(is_confirm=True).all()
    startups = Startup.query.filter_by(is_confirm=True).all()
    sorted_movies = sorted(movies, key=lambda movie: movie.liked_count, reverse=True)
    sorted_animes = sorted(animes, key=lambda anime: anime.liked_count, reverse=True)
    sorted_articles = sorted(articles, key=lambda article: article.liked_count, reverse=True)
    sorted_photos = sorted(photos, key=lambda photo: photo.liked_count, reverse=True)
    sorted_courses = sorted(courses, key=lambda course: course.liked_count, reverse=True)
    sorted_startups = sorted(startups, key=lambda startup: startup.liked_count, reverse=True)
    return render_template(
            'main/rank.html',
            movies=sorted_movies[:20],
            animes=sorted_animes[:20],
            photos=sorted_photos[:20],
            articles=sorted_articles[:20],
            courses=sorted_courses[:20],
            startups=sorted_startups[:20]
            )

app/templates/main/animes.html
{% extends 'main/base.html' %} 
{% block title %}动 漫{% endblock %}
{% block page_content %}
		<div class="index_tu index_morecontent">
		<div class="index_title">
			<div class="index_tag tag2">动漫</div>
		</div>
		<div class="index_tu_box">
			{% for anime in animes %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_anime', id=anime.id) }}"><img src="{{ anime.upload_url }}"></a></div>
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_anime', id=anime.id) }}">{{ anime.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ anime.a_time }}</span>
							<span>{{ anime.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ anime.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
			<div class="index_tu_content index_blank"></div>
			<div class="index_tu_content index_blank"></div>
		</div>
	</div>
{% endblock %}

app/templates/main/article.html
{% extends 'main/base.html' %}
{% block title %}{{ article.present_name }}-{{ article.author_name }}{% endblock %}
	{% block page_content %}
	<div class="second_box">
		<div class="second_head">
			<span class="second_head_title">{{ article.present_name }}</span>
			<span class="second_head_author">{{ article.a_time }}/{{ article.author_name }}</span>
		</div>
		<div class="second_content second_article">{{ article.description|safe }}</div>
		<a href="{{ article.upload_url }}" class="second_download">点击下载</a>
	    <!-- 多说评论框 start -->
	    <div class="ds-thread" data-thread-key="r{{ article.id }}" data-title="{{ article.present_name }}" data-url="{{ url_for('main.get_article', id=article.id) }}"></div>
	    <!-- 多说评论框 end -->
	    <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
	    <script type="text/javascript">
	    var duoshuoQuery = {short_name:"wenhuajie"};
	        (function() {
	            var ds = document.createElement('script');
	            ds.type = 'text/javascript';ds.async = true;
	            ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
	            ds.charset = 'UTF-8';
	            (document.getElementsByTagName('head')[0] 
	             || document.getElementsByTagName('body')[0]).appendChild(ds);
	        })();
	        </script>
	    <!-- 多说公共JS代码 end -->
	</div>
	{% endblock %}
	{% block captcha %}
	<div class="c_container" id="captcha_container">
		<div class="c_content">
			<form method="post" action="{{ url_for('main.validate_capthca') }}">
				<div class="c_box">
				<div id="captcha"></div>
				<div class="c_box">
					<!-- <button id="submit-button">提交</button> -->
				</div>
				<script src="http://static.geetest.com/static/tools/gt.js"></script>
				<script>
				    // var handler = function (captchaObj) {
				    //      // 将验证码加到id为captcha的元素里
				    //      captchaObj.appendTo("#captcha");
				    //  };
				    // $.ajax({
				    //     // 获取id，challenge，success（是否启用failback）
				    //     url: "/main/getcaptcha",
				    //     type: "get",
				    //     dataType: "json", // 使用jsonp格式
				    //     success: function (data) {
				    //         // 使用initGeetest接口
				    //         // 参数1：配置参数，与创建Geetest实例时接受的参数一致
				    //         // 参数2：回调，回调的第一个参数验证码对象，之后可以使用它做appendTo之类的事件
				    //         initGeetest({
				    //             gt: data.gt,
				    //             challenge: data.challenge,
				    //             product: "embed", // 产品形式
				    //             offline: !data.success
				    //         }, handler);
				    //     }
				    // });
				</script>
				</div>
				<div class="c_confirm"><button id="c_confirm_btn">确认</button></div>
			</form>
		</div>
	</div>
	{% endblock %}
{% block vote_button %}
<div class="second_vote">
	<button class="second_vote_bt" id="vote_article">投票</button>
</div>
<script>
		var article = document.getElementById('vote_article');
		var id = window.location.pathname.split('/')[3];
		article.addEventListener("click", function(){
		fetch("/main/article/" + id + "/vote/", {
			method: 'GET',
		}).then(res => {
			if (res.ok) {
				alert("投票成功！")
			} else {
				alert("每个 IP 仅能投一次！")
			}
		})
	});
	</script>
<!-- <script src="../../../static/js/second.js"></script> -->
{% endblock %}
{% block flash_message %}
		{% with messages = get_flashed_messages() %}
		{% if messages %}
		<div class="submite_flash" id="submit_flash">
			{% for message in messages %}
			<div class="submite_message">{{ message }}</div>
			{% endfor %}
			<div class="submit_close" id="submit_close">x</div>
		</div>
		{% endif %}
		{% endwith %}
{% endblock %}

app/templates/main/articles.html
{%extends 'main/base.html' %}
{% block title %}文 章{% endblock %}
{% block page_content %}
	<div class="index_article index_morecontent">
	<div class="index_title">
		<div class="index_tag tag2">网文</div>
	</div>
	<div class="index_article_box">
		{% for article in articles %}
		<div class="index_article_content">
			<div class="index_article_line">
				<a class="index_article_title" href="{{ url_for('main.get_article', id=article.id) }}">{{ article.present_name }}</a>
				<div class="index_article_info">
					<div class="index_author_name">{{ article.author_name }} ／文</div>
					<div class="index_liked_count">{{ article.liked_count }}</div>
					<div class="index_timestamp">{{ article.a_time }}</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	</div>
	
{% endblock %}

app/templates/main/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="../../../static/img/favicon.ico" type="image/x-icon" />
    <title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <!-- <script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script> -->
</head>
<body>
	<div class="content">
		{% block flash_message %}{% endblock %}
		{% block guide %}
			<div class="guide">
				<div class="button_list">
                    <button class="first first_page" id="first_page" onclick="location.href='/main/'">首页</button><button class="second upload" id="upload" onclick="location.href='/main/upload'">作品上传</button><button class="third rank" id="rank" onclick="location.href='/main/rank'">票数排行</button>
				</div>
			</div>
		{% endblock %}
		{% block page_content %}{% endblock %}
	</div>
	{% block captcha %}{% endblock %}
	{% block vote_button %}{% endblock %}
</body>
</html>

app/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}文化节{% endblock %}
{% block page_content %}
	<div class="index_banner">
		<img class="index_banner_img" src="/static/img/banner1.png">
	</div>
	<div class="index_notice">
		<div class="index_title">
			<div class="index_tag tag1">通知</div>
			<a class="index_more" href="{{ url_for('main.notices') }}">更多 ></a>
		</div>
		<div class="index_notice_box">
		{% for notice in notices %}
			<div class="index_notice_content">
                <div class="index_notice_dot"></div>
				<a class="index_notice_time">{{ notice.a_time }}</a>
                <div class="index_notice_line"><a href="{{ url_for('main.get_notice', id=notice.id) }}">{{ notice.name }}</a></div>
			</div>
		{% endfor %}
		</div>
	</div>

	<div class="index_tu">
		<div class="index_title">
			<div class="index_tag tag2">微课程</div>
			<a class="index_more" href="{{ url_for('main.courses') }}">更多 ></a>
		</div>
		<div class="index_tu_box">
			{% for course in courses %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_course', id=course.id) }}"><img src="http://ohr9krjig.bkt.clouddn.com/whj/u.png"></a></div>
				<!--<div class="index_tu_img"><a href="{{ url_for('main.get_course', id=course.id) }}"><img src="{{ course.upload_url }}"></a></div>-->
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_course', id=course.id) }}">{{ course.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ course.a_time }}</span>
							<span>{{ course.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ course.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="index_tu">
		<div class="index_title">
			<div class="index_tag tag2">摄影</div>
			<a class="index_more" href="{{ url_for('main.photos') }}">更多 ></a>
		</div>
		<div class="index_tu_box">
			{% for photo in photos %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_photo', id=photo.id) }}"><img src="http://ohr9krjig.bkt.clouddn.com/whj/c.png"></a></div>
				<!--<div class="index_tu_img"><a href="{{ url_for('main.get_photo', id=photo.id) }}"><img src="{{ photo.first_photo }}"></a></div>-->
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_photo', id=photo.id) }}">{{ photo.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ photo.a_time }}</span>
							<span>{{ photo.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ photo.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="index_tu">
		<div class="index_title">
			<div class="index_tag tag1">动漫</div>
			<a class="index_more" href="{{ url_for('main.animes') }}">更多 ></a>
		</div>
		<div class="index_tu_box">
			{% for anime in animes %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_anime', id=anime.id) }}"><img src="http://ohr9krjig.bkt.clouddn.com/whj/n.png"></a></div>
				<!--<div class="index_tu_img"><a href="{{ url_for('main.get_anime', id=anime.id) }}"><img src="{{ anime.upload_url }}"></a></div>-->
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_anime', id=anime.id) }}">{{ anime.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ anime.a_time }}</span>
							<span>{{ anime.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ anime.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="index_tu">
		<div class="index_title">
			<div class="index_tag tag1">微视频</div>
			<a class="index_more" href="{{ url_for('main.movies') }}">更多 ></a>
		</div>
		<div class="index_tu_box">
			{% for movie in movies %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_movie', id=movie.id) }}"><img src="{{ movie.img_url }}"></a></div>
				<!-- <div class="index_tu_img"><a href="{{ url_for('main.get_movie', id=movie.id) }}"><img src="{{ movie.upload_url }}"></a></div> -->
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_movie', id=movie.id) }}">{{ movie.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ movie.a_time }}</span>
							<span>{{ movie.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ movie.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="index_article">
		<div class="index_title">
			<div class="index_tag tag2">网文</div>
			<a class="index_more" href="{{ url_for('main.articles') }}">更多 ></a>
		</div>
		<div class="index_article_box">
			{% for article in articles %}
			<div class="index_article_content">
				<div class="index_article_line">
					<a class="index_article_title" href="{{ url_for('main.get_article', id=article.id) }}">{{ article.present_name }}</a>
					<div class="index_article_info">
						<div class="index_author_name">{{ article.author_name }} ／文</div>
						<div class="index_liked_count">{{ article.liked_count }}</div>
						<div class="index_timestamp">{{ article.a_time }}</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	

	<div class="index_tu">
		<div class="index_title">
			<div class="index_tag tag1 longtag">网络创新创业</div>
			<a class="index_more" href="{{ url_for('main.startups') }}">更多 ></a>
		</div>
		<div class="index_tu_box">
			{% for startup in startups %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_startup', id=startup.id) }}"><img src="http://ohr9krjig.bkt.clouddn.com/whj/u.png"></a></div>
				<!--<div class="index_tu_img"><a href="{{ url_for('main.get_startup', id=startup.id) }}"><img src="{{ startup.upload_url }}"></a></div>-->
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_startup', id=startup.id) }}">{{ startup.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ startup.a_time }}</span>
							<span>{{ startup.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ startup.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<script src="../../static/js/index.js"></script>
 {% endblock %}

app/templates/main/movies.html
{% extends 'main/base.html' %}
{% block title %}微视频{% endblock %}
{% block page_content %}
	<div class="index_tu index_morecontent">
		<div class="index_title">
			<div class="index_tag tag1">微视频</div>
		</div>
		<div class="index_tu_box">
			{% for movie in movies %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_movie', id=movie.id) }}"><img src="{{ movie.upload_url }}"></a></div>
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_movie', id=movie.id) }}">{{ movie.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ movie.a_time }}</span>
							<span>{{ movie.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ movie.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
			<div class="index_tu_content index_blank"></div>
			<div class="index_tu_content index_blank"></div>
		</div>
	</div>
{% endblock %}

app/templates/main/notice.html
{% extends 'main/base.html' %}
{% block title %}通知-{{ notice.name }}{% endblock %}
	{% block page_content %}
	<div class="second_box">
		<div class="second_head">
			<span class="second_head_title second_notice">{{ notice.name }}</span>
			<span class="second_head_author second_notice_time">{{ notice.a_time }}</span>
		</div>
		<p class="second_description">{{ notice.description }}</p>
		<div class="second_content">{{ notice.body | safe }}</div>
	</div>
	{% endblock %}
	{% block vote_button %}
	<div class="second_vote">
		<a href="{{ notice.appendix }}" class="second_download" style="margin-top:15px;">下载附件</a>
	</div>
	{% endblock %}

app/templates/main/startups.html
{% extends 'main/base.html' %}
{% block title %}网络创新创业{% endblock %}
{% block page_content %}
	<div class="index_tu index_morecontent">
		<div class="index_title">
			<div class="index_tag tag1 longtag">网络创新创业</div>
		</div>
		<div class="index_tu_box">
			{% for startup in startups %}
			<div class="index_tu_content">
				<div class="index_tu_img"><a href="{{ url_for('main.get_startup', id=startup.id) }}"><img src="{{ startup.video_url }}"></a></div>
				<div class="index_tu_info_box">
					<div class="index_tu_info">
						<div class="index_tu_title_name"><a href="{{ url_for('main.get_startup', id=startup.id) }}">{{ startup.present_name }}</a>
						</div>
						<div class="index_tu_time_name">
							<span>{{ startup.a_time }}</span>
							<span>{{ startup.author_name }}</span>
						</div>
					</div>
					<div class="index_tu_like">
						<img src="../../static/img/heart.png">
						<div class="index_liked_count"><a>{{ startup.liked_count }}</a></div>
					</div>
				</div>
			</div>
			{% endfor %}
			<div class="index_tu_content index_blank"></div>
			<div class="index_tu_content index_blank"></div>
		</div>
	</div>
{% endblock %}